[package]
name = "apistos-schemars_derive"
description = "Macros for #[derive(JsonSchema)], for use with schemars"
repository = "https://github.com/netwo-io/apistos-schemars"
version = "0.8.21"
edition = "2024"
license = "MIT"
readme = "README.md"
keywords = ["rust", "json-schema", "serde"]
rust-version = "1.85.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
serde_derive_internals = "0.29"

[dev-dependencies]
pretty_assertions = "1.2.1"
